services:

  service-registry:
  build: ./service-registry
  image: yash9912/task-manager-registry
  ports:
    - "8761:8761"
  networks:
    - microservices-net
  environment:
    - SPRING_PROFILES_ACTIVE=docker
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:8761/eureka/apps"]
    interval: 10s
    timeout: 5s
    retries: 10

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "0.0.0.0", "--protected-mode", "no"]
    networks:
      - microservices-net

  auth-service:
    build: ./auth-service
    image: yash9912/task-manager-auth
    ports:
      - "8085:8081"
    depends_on:
       service-registry:
         condition: service_healthy
       redis:
         condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices-net

  task-service:
    build: ./task-service
    image: yash9912/task-manager-task
    ports:
      - "8082:8082"
    depends_on:
      - service-registry
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices-net

  api-gateway:
    build: ./api-gateway
    image: yash9912/task-manager-gateway
    ports:
      - "8090:8080"
    depends_on:
       service-registry :
          condition: service_started
       auth-service :
          condition: service_started
       task-service :
          condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
