version: "3.9"

services:

  service-registry:
    build: ./service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    networks:
      - microservices-net
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "0.0.0.0", "--protected-mode", "no"]
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8085:8081"
    depends_on:
      - service-registry
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices-net

  task-service:
    build: ./task-service
    container_name: task-service
    ports:
      - "8082:8082"
    depends_on:
       service-registry :
         condition: service_started
       redis :
         condition: service_healthy
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices-net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8090:8080"
    depends_on:
      - service-registry
      - auth-service
      - task-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

